services:
  zookeeper:
    image: bitnami/zookeeper:latest
    environment:
      - ZOO_ENABLE_AUTH=no
      - ALLOW_ANONYMOUS_LOGIN=yes
    ports:
      - "2181:2181"
    volumes:
      - zookeeper-data:/bitnami

  kafka:
    image: bitnami/kafka:latest
    ports:
      - "9092:9092"
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
      - ALLOW_PLAINTEXT_LISTENER=yes
    depends_on:
      - zookeeper
    volumes:
      - kafka-data:/bitnami

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  backend:
    build:
      context: D:\\projects\\NodenKafka\\backend
      dockerfile: Dockerfile
    ports:
      - "3001:3000"
    environment:
      - KAFKA_BROKER=kafka:9092
      - MONGO_URL=mongodb://mongo:27017/financialDb
    depends_on:
      - kafka
      - mongo
    volumes:
      - ./backend/:/usr/src/app
      - /usr/src/app/node_modules

  frontend:
    build:
      context: D:\\projects\\NodenKafka\\frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_API_URL=http://localhost:3000
      - CI=true
    depends_on:
      - backend
    volumes:
      - D:\\projects\\NodenKafka\\frontend:/usr/src/app

volumes:
  mongo-data:
  zookeeper-data:
  kafka-data:
  node_modules:
